name: Sismaya SIM

on:
  push:
    branches: [ "staging" ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/sismedika/app/sismaya-sim
          git stash
          git pull origin staging
          npm i
          npm ci
          npm run build